name: Keep alive cron job
on:
  schedule:
    - cron: '0 0 * * *' # daily https://crontab.guru/#0_0_*_*_*
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: |
          response=$(curl --request GET --url '${{ secrets.SITE_URL }}/api/keep-alive' --location)
          echo "Response: $response"
